import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/provider";
import { GeistSans } from "geist/font/sans";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: {
    default: "Next Auth",
    template: "%s | Next Auth",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Toaster richColors />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
